### ISSUE TITLE
Auto Approve Yes in config

### ISSUE THREAD

**Issue by donavanbecker** [hunghg255/ctun#1]
Any chance you can add a config that would automatically accept this?

```🔥 Your installation of cloudflared software constitutes a symbol of your signature
   indicating that you accept the terms of the Cloudflare License, Terms and Privacy Policy.

❯ License:         https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/license/
❯ Terms:           https://www.cloudflare.com/terms/
❯ Privacy Policy:  https://www.cloudflare.com/privacypolicy/


❯ Do you agree with the above terms and wish to install the binary from GitHub?
● Yes / ○ No
```

I am trying to use this as an npm dependency.

**Comment by hunghg255** [comment]
@donavanbecker Hi, I exported a new func `startTunnelAuto` disabled prompt, you can check the newest version

**Comment by donavanbecker** [comment]
Thank @hunghg255!! So just add `startTunnelAuto: true` in the config?

**Comment by donavanbecker** [comment]
Nevermind, Figured it out. Thanks!

**Comment by donavanbecker** [comment]
So with `startTunnelAuto`, is it expecting that the tunnel is already installed? or is auto installing.

**Comment by hunghg255** [comment]
it auto install cloudflare.

Vào CN, 31 thg 12, 2023 lúc 06:27 Donavan Becker ***@***.***>
đã viết:

**Comment by donavanbecker** [comment]
Thanks. Should I expect to see any logs when it is installing? Currently nothing shows so looks like nothing is happening.

**Comment by hunghg255** [comment]
you can add a log before that get url. 😁

**Comment by donavanbecker** [comment]
> you can add a log before that get url. 😁

when I get the url, it is just blank. see below:
```
Starting Tunnel with Options: {"port":8581,"hostname":"198.19.249.2","protocol":"http","verifyTLS":false}
Tunnel URL: {}
```
all coming from this code:
[homebridge-cloudflared-tunnel>createTunnel](https://github.com/donavanbecker/homebridge-cloudflared-tunnel/blob/d396e2cc3193ba24a76336e8ed5c81435b3fedfd/src/platform.ts#L126-L146)
Just added a 5 min wait to see if that will help with waiting for the install process.

**Comment by donavanbecker** [comment]
could you add logs showing the install of cloudflared?

**Comment by hunghg255** [comment]
> could you add logs showing the install of cloudflared?

@donavanbecker oke, I just publish new version add spin when install cloudflare https://github.com/hunghg255/ctun/commit/9316f9d7e2efdd8b623fcbfb666b923f2b5e926d

**Comment by donavanbecker** [comment]
Thanks, but I am not seeing any spinner or install happening.

```
[12/30/2023, 11:21:28 PM] [CloudflaredTunnel] Starting Tunnel with Options: {"port":8581,"hostname":"198.19.249.2","protocol":"http","verifyTLS":false}
[12/30/2023, 11:21:28 PM] [CloudflaredTunnel] Starting Tunnel in Auto Install Mode
[12/30/2023, 11:21:28 PM] [CloudflaredTunnel] Started Tunnel in Auto Install Mode
[12/30/2023, 11:21:28 PM] [CloudflaredTunnel] Waiting 1 minute for tunnel to install and start
[12/30/2023, 11:22:28 PM] [CloudflaredTunnel] Tunnel URL: {}
```

**Comment by donavanbecker** [comment]
and now when I try to use `startTunnel` again, I am not seeing the confirmation that I was seeing before:

```
[12/30/2023, 11:25:41 PM] [CloudflaredTunnel] Starting Tunnel with Options: {"port":8581,"hostname":"198.19.249.2","protocol":"http","verifyTLS":false}
[12/30/2023, 11:25:41 PM] [CloudflaredTunnel] Starting Tunnel in Manual Install Mode
[12/30/2023, 11:25:41 PM] Homebridge v1.7.0 (HAP v0.11.1) (CloudflaredTunnel) is running on port 58111.
[12/30/2023, 11:25:41 PM] [CloudflaredTunnel] Started Tunnel in Manual Install Mode
[12/30/2023, 11:25:41 PM] [CloudflaredTunnel] Waiting 1 minute for tunnel to install and start
[12/30/2023, 11:26:41 PM] [CloudflaredTunnel] Tunnel URL: {}
```

**Comment by donavanbecker** [comment]
by the way thank you so much so far, for what you have done.

**Comment by hunghg255** [comment]
https://github.com/hunghg255/ctun/assets/42096908/4e8a99a1-7dbb-4a0c-b1ff-ebdeaf1b2224

@donavanbecker yea, I checked your code. I tested my local it work.

**Comment by hunghg255** [comment]
I imported lazy cloudflare script to reduce size bundle for package, so you will see it delayed a bit

```ts
export async function startTunnelAuto(
  opts: TunnelOptions,
): Promise<undefined | Tunnel> {
  const {
    installCloudflared,
    startCloudflaredTunnel,
    cloudflaredBinPath,
  } = await import("./cloudflared");
  ```

**Comment by hunghg255** [comment]
> and now when I try to use `startTunnel` again, I am not seeing the confirmation that I was seeing before:
> 
> ```
> [12/30/2023, 11:25:41 PM] [CloudflaredTunnel] Starting Tunnel with Options: {"port":8581,"hostname":"198.19.249.2","protocol":"http","verifyTLS":false}
> [12/30/2023, 11:25:41 PM] [CloudflaredTunnel] Starting Tunnel in Manual Install Mode
> [12/30/2023, 11:25:41 PM] Homebridge v1.7.0 (HAP v0.11.1) (CloudflaredTunnel) is running on port 58111.
> [12/30/2023, 11:25:41 PM] [CloudflaredTunnel] Started Tunnel in Manual Install Mode
> [12/30/2023, 11:25:41 PM] [CloudflaredTunnel] Waiting 1 minute for tunnel to install and start
> [12/30/2023, 11:26:41 PM] [CloudflaredTunnel] Tunnel URL: {}
> ```

because your computer installed cloudflare

**Comment by donavanbecker** [comment]
you know what, I was trying this in a docker image and that is why it wasn't doing anything. Is there anything that can be done besides creating a specific docker image for cloudflare?

**Comment by hunghg255** [comment]
> you know what, I was trying this in a docker image and that is why it wasn't doing anything. Is there anything that can be done besides creating a specific docker image for cloudflare?

I have not tried with docker yet,

**Comment by hunghg255** [comment]
you can try https://hub.docker.com/r/cloudflare/cloudflared

**Comment by donavanbecker** [comment]
> because your computer installed cloudflare

if that is the case maybe a log that would display where cloudflare is installed? 

I was able to get the spinner and `Installing cloudflared`, but never saw  `Installed cloudflared successfully`

**Comment by hunghg255** [comment]
> > because your computer installed cloudflare
> 
> if that is the case maybe a log that would display where cloudflare is installed?
> 
> I was able to get the spinner and `Installing cloudflared`, but never saw `Installed cloudflared successfully`

oh you can check the folder cloudflare
In my mac: `/var/folders/bb/yxj478wj6kn4936xr8wj4c4h0000gn/T/node-untun/cloudflared.2023.7.3`

**Comment by donavanbecker** [comment]
> you can try https://hub.docker.com/r/cloudflare/cloudflared

yeah I could just recommend that.

**Comment by donavanbecker** [comment]
> > > because your computer installed cloudflare
> > 
> > 
> > if that is the case maybe a log that would display where cloudflare is installed?
> > I was able to get the spinner and `Installing cloudflared`, but never saw `Installed cloudflared successfully`
> 
> oh you can check the folder cloudflare In my mac: `/var/folders/bb/yxj478wj6kn4936xr8wj4c4h0000gn/T/node-untun/cloudflared.2023.7.3`

I wasn't able to find it. maybe having a reinstall option?
